name: Run autotests


on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Select tests to run
        required: true
        type: choice
        default: all
        options:
          - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Copy sourse code
        uses: actions/checkout@v4
      - name: Set up Python env
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD/src" >> $GITHUB_ENV
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -v
